In [1]:
import numpy as np
import pandas as pd

In [2]:
import_df = pd.read_csv('import_cleaned.csv')
export_df = pd.read_csv('export_cleaned.csv')

In [3]:
import_df.head()

                country  import  year code
0                 China   55.89  2017  CHN
1         United States   19.14  2017  USA
2  United Arab Emirates   16.68  2017  ARE
3          Saudi Arabia   15.44  2017  SAU
4           Switzerland   14.93  2017  CHE

In [4]:
export_df.head()

                country  export  year code
0         United States   34.83  2017  USA
1  United Arab Emirates   20.78  2017  ARE
2             Hong Kong   10.78  2017  HKG
3                 China    9.10  2017  CHN
4             Singapore    7.52  2017  SGP

In [5]:
deficit_df = pd.merge(import_df, export_df, how='inner', on=['country','code','year'])
deficit_df.head()

                country  import  year code    export
0                 China   55.89  2017  CHN   9.10000
1         United States   19.14  2017  USA  34.83000
2  United Arab Emirates   16.68  2017  ARE  20.78000
3          Saudi Arabia   15.44  2017  SAU   3.78000
4           Switzerland   14.93  2017  CHE   0.67344

In [6]:
deficit_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 184 entries, 0 to 183
Data columns (total 5 columns):
country    184 non-null object
import     184 non-null float64
year       184 non-null int64
code       184 non-null object
export     184 non-null float64
dtypes: float64(2), int64(1), object(2)
memory usage: 8.6+ KB

In [7]:
deficit_df['deficit'] = deficit_df['export'] - deficit_df['import']
deficit_df.head()

                country  import  year code    export   deficit
0                 China   55.89  2017  CHN   9.10000 -46.79000
1         United States   19.14  2017  USA  34.83000  15.69000
2  United Arab Emirates   16.68  2017  ARE  20.78000   4.10000
3          Saudi Arabia   15.44  2017  SAU   3.78000 -11.66000
4           Switzerland   14.93  2017  CHE   0.67344 -14.25656

In [8]:
deficit_df['deficit'].sum()

-104.68632123900001

In [9]:
deficit_df.sort_values(by='deficit', ascending=False)[:5]

                 country    import  year code  export   deficit
1          United States  19.14000  2017  USA   34.83  15.69000
64            Bangladesh   0.45941  2017  BGD    5.81   5.35059
2   United Arab Emirates  16.68000  2017  ARE   20.78   4.10000
73                 Nepal   0.31125  2017  NPL    4.35   4.03875
25        United Kingdom   3.43000  2017  GBR    6.69   3.26000

In [10]:
deficit_df.sort_values(by='deficit')[:5]

        country  import  year code   export   deficit
0         China   55.89  2017  CHN  9.10000 -46.79000
4   Switzerland   14.93  2017  CHE  0.67344 -14.25656
3  Saudi Arabia   15.44  2017  SAU  3.78000 -11.66000
6          Iraq   11.51  2017  IRQ  0.96683 -10.54317
5     Indonesia   12.21  2017  IDN  2.75000  -9.46000

## Visualization

In [11]:
import plotly
import plotly.graph_objs as go
from plotly import tools

In [12]:
plotly.offline.init_notebook_mode(connected=True)

In [15]:
data = [dict(
    type = 'choropleth',
    locations = deficit_df['code'],
    z = deficit_df['deficit'],
    text = deficit_df['country'],
    colorscale = 'Viridis',
    #reversescale = True,
    colorbar = dict(
        tickprefix = '$',
        title = 'Trade Deficit<br>Billions US$',
    )
)]

layout = dict(
    title = 'Trade Deficit of India from Countries around the World in USD Billions',
    geo = dict(
        showframe = False,
        #showcoastlines = False,
        projection = dict(
            type = 'Mercator'
        )
    )
)

plotly.offline.iplot(dict(data = data, layout = layout), validate=False)

In [17]:
plotly.offline.plot(dict(data = data, layout = layout), validate=False, show_link=False, include_plotlyjs=False, output_type='div')

'<div id="5615db20-3b6e-496c-b904-9afedb53394f" style="height: 100%; width: 100%;" class="plotly-graph-div"></div><script type="text/javascript">window.PLOTLYENV=window.PLOTLYENV || {};window.PLOTLYENV.BASE_URL="https://plot.ly";Plotly.newPlot("5615db20-3b6e-496c-b904-9afedb53394f", [{"type": "choropleth", "locations": ["CHN", "USA", "ARE", "SAU", "CHE", "IDN", "IRQ", "AUS", "DEU", "HKG", "JPN", "IRN", "MYS", "NGA", "RUS", "QAT", "SGP", "ZAF", "THA", "KWT", "FRA", "BEL", "VEN", "BRA", "CAN", "GBR", "ITA", "VNM", "AGO", "OMN", "MEX", "ARG", "GHA", "NLD", "UKR", "PER", "ISR", "CHL", "BWA", "ESP", "SWE", "EGY", "FIN", "DZA", "TUR", "KAZ", "ZMB", "MOZ", "TZA", "JOR", "AUT", "NOR", "MAR", "PHL", "LKA", "GNQ", "POL", "IRL", "BFA", "NZL", "BOL", "CZE", "SEN", "DOM", "BGD", "COL", "GIN", "DNK", "PAK", "AZE", "BRN", "SDN", "AFG", "NPL", "BHR", "ROU", "GAB", "BTN", "CMR", "HUN", "BEN", "ECU", "LAO", "PRT", "LTU", "PNG", "TGO", "PRY", "BLR", "BGR", "MLI", "TUN", "MDG", "UZB", "SVN", "YEM", "SUR", "SSD", "SVK", "GRC", "LSO", "CRI", "TCD", "KEN", "SLB", "ZWE", "EST", "LVA", "UGA", "NAM", "TTO", "TJK", "KHM", "PAN", "LUX", "LBR", "ALB", "ETH", "KGZ", "LBN", "MKD", "LBY", "HRV", "GEO", "COM", "SYR", "URY", "NER", "SRB", "SLE", "MWI", "MUS", "TKM", "MLT", "GTM", "HND", "BDI", "CYP", "NCL", "SLV", "SWZ", "BIH", "MAC", "CUW", "HTI", "CYM", "ISL", "GUY", "MDV", "NIC", "JAM", "DJI", "RWA", "SOM", "MRT", "CAF", "ERI", "CUB", "MNG", "BLZ", "MDA", "PLW", "SYC", "SMR", "VGB", "ARM", "ABW", "FJI", "LCA", "WSM", "DMA", "GRD", "MNP", "AIA", "MHL", "BRB", "PYF", "ATG", "GRL", "MNE", "COK", "GIB", "TUV", "VUT"], "z": [-46.79, 15.689999999999998, 4.100000000000001, -11.66, -14.25656, -9.46, -10.54317, -7.140000000000001, -3.5600000000000005, 2.539999999999999, -4.69, -5.68, -2.64, -4.76, -4.6, -4.9629, 2.26, -2.1399999999999997, -2.4699999999999998, -3.7278599999999997, -1.2399999999999998, -0.1200000000000001, -4.22232, -1.67, -1.7599999999999998, 3.2600000000000002, 0.7399999999999998, 2.79, -2.88949, -0.8499999999999999, 0.1599999999999997, -1.3700099999999997, -1.3996399999999998, 2.16, -1.51835, -1.19332, 0.8500000000000001, -0.8175199999999999, -1.20143, 1.56, -0.5406900000000001, 0.83136, -0.7486600000000001, -0.37899000000000005, 2.7911099999999998, -0.69636, -0.56774, -0.07024999999999992, 0.30989999999999995, -0.3487199999999999, -0.33809, -0.36252, -0.2928000000000001, 0.62084, 2.57965, -0.55806, 0.5662300000000001, -0.15790999999999994, -0.42163000000000006, -0.24258999999999997, -0.42348, -0.19275000000000003, 0.04385, -0.32569000000000004, 5.3505899999999995, 0.26694000000000007, -0.15233000000000002, 0.16477000000000008, 0.76603, -0.32798000000000005, -0.31535, 0.30056, 0.17546000000000006, 4.038749999999999, 0.09030999999999995, -0.02816000000000002, -0.21311, 0.12635999999999997, -0.054210000000000036, 0.09792000000000001, 0.18624000000000002, 0.04147999999999999, -0.13348000000000002, 0.38797000000000004, -0.06208999999999999, -0.10365999999999999, 0.21540000000000006, -0.0076899999999999885, -0.08880000000000002, 0.017360000000000014, -0.020290000000000002, 0.09395, 0.04915000000000001, -0.0027699999999999947, 0.12118, 0.29179, -0.056909999999999995, -0.06493, 0.04446, 0.22280000000000003, -0.04060000000000001, 0.02993, -0.03863, 1.28681, -0.048906609999999996, 0.07937, 0.016170000000000004, 0.03776, 0.34209, -0.011269999999999992, 0.027329999999999993, -0.02025, 0.049499999999999995, 0.14109000000000002, -0.02816, 0.16893999999999998, -0.01329, 0.5145899999999999, -0.00929, 0.15867, -0.015340000000000003, 0.06831, 0.10545, 0.02903, -0.00706, 0.08839, 0.09745999999999999, 0.06910000000000001, 0.0235, 0.044980000000000006, 0.15606, 0.69371, 0.033780000000000004, 0.13908999999999996, 0.2054, 0.09983, 0.020110000000000003, 0.0746, -0.002, 0.041929999999999995, 0.01703, 0.0038800000000000015, 0.000720000000000001, 0.026830000000000003, 0.06671, -0.0022199999999999993, -0.0007499999999999998, 0.012820000000000002, 0.1481, 0.05726, 0.03597000000000001, 0.19295, 0.06817999999999999, 0.3479300000000001, 0.04843, 0.02597, 0.004090000000000001, 0.03048, 0.0104, 0.0096, 0.00405, -0.00071901, 0.02866976, -0.00043721000000000005, 8.127000000000004e-05, 0.02607793, 0.00483792, 0.04163281, 0.00262512, 0.00147151, 0.0011972299999999999, 0.00213892, -0.00013246, 0.00023839, -5.5100000000000004e-05, 0.01001319, 0.00556776, 0.00165648, -3.5099999999999994e-06, 0.0429801, 0.00015916, 0.15616439999999998, 6.076e-05, -48.99831], "text": ["China", "United States", "United Arab Emirates", "Saudi Arabia", "Switzerland", "Indonesia", "Iraq", "Australia", "Germany", "Hong Kong", "Japan", "Iran", "Malaysia", "Nigeria", "Russia", "Qatar", "Singapore", "South Africa", "Thailand", "Kuwait", "France", "Belgium", "Venezuela", "Brazil", "Canada", "United Kingdom", "Italy", "Vietnam", "Angola", "Oman", "Mexico", "Argentina", "Ghana", "Netherlands", "Ukraine", "Peru", "Israel", "Chile", "Botswana", "Spain", "Sweden", "Egypt", "Finland", "Algeria", "Turkey", "Kazakhstan", "Zambia", "Mozambique", "Tanzania", "Jordan", "Austria", "Norway", "Morocco", "Philippines", "Sri Lanka", "Equatorial Guinea", "Poland", "Ireland", "Burkina Faso", "New Zealand", "Bolivia", "Czech Republic", "Senegal", "Dominican Republic", "Bangladesh", "Colombia", "Guinea", "Denmark", "Pakistan", "Azerbaijan", "Brunei", "Sudan", "Afghanistan", "Nepal", "Bahrain", "Romania", "Gabon", "Bhutan", "Cameroon", "Hungary", "Benin", "Ecuador", "Laos", "Portugal", "Lithuania", "Papua New Guinea", "Togo", "Paraguay", "Belarus", "Bulgaria", "Mali", "Tunisia", "Madagascar", "Uzbekistan", "Slovenia", "Yemen", "Suriname", "South Sudan", "Slovakia", "Greece", "Lesotho", "Costa Rica", "Chad", "Kenya", "Solomon Islands", "Zimbabwe", "Estonia", "Latvia", "Uganda", "Namibia", "Trinidad And Tobago", "Tajikistan", "Cambodia", "Panama", "Luxembourg", "Liberia", "Albania", "Ethiopia", "Kyrgyzstan", "Lebanon", "Macedonia", "Libya", "Croatia", "Georgia", "Comoros", "Syria", "Uruguay", "Niger", "Serbia", "Sierra Leone", "Malawi", "Mauritius", "Turkmenistan", "Malta", "Guatemala", "Honduras", "Burundi", "Cyprus", "New Caledonia", "El Salvador", "Swaziland", "Bosnia And Herzegovina", "Macau", "Curacao", "Haiti", "Cayman Islands", "Iceland", "Guyana", "Maldives", "Nicaragua", "Jamaica", "Djibouti", "Rwanda", "Somalia", "Mauritania", "Central African Republic", "Eritrea", "Cuba", "Mongolia", "Belize", "Moldova", "Palau", "Seychelles", "San Marino", "British Virgin Islands", "Armenia", "Aruba", "Fiji", "Saint Lucia", "Samoa", "Dominica", "Grenada", "Northern Mariana Islands", "Anguilla", "Marshall Islands", "Barbados", "French Polynesia", "Antigua and Barbuda", "Greenland", "Montenegro", "Cook Islands", "Gibraltar", "Tuvalu", "Vanuatu"], "colorscale": "Viridis", "colorbar": {"tickprefix": "$", "title": "Trade Deficit<br>Billions US$"}}], {"title": "Trade Deficit of India from Countries around the World in USD Billions", "geo": {"showframe": false, "projection": {"type": "Mercator"}}}, {"showLink": false, "linkText": "Export to plot.ly"})</script>'

In [19]:
# create svg file
#plotly.offline.iplot(dict(data = data, layout = layout), validate=False, show_link=False, image='svg')